[workspace]
resolver = "2"
members = [
    "crates/ctrlvim-types",
    "crates/ctrlvim-text",
    "crates/ctrlvim-options",
    "crates/ctrlvim-editor",
    "crates/ctrlvim-vimscript",
    "crates/ctrlvim-treesitter",
    "crates/ctrlvim-markdown",
    "crates/ctrlvim-api-macro",
    "crates/ctrlvim-api",
    "crates/ctrlvim-lua",
    "crates/ctrlvim-async",
    "crates/ctrlvim-core",
    "crates/ctrlvim-tui",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.80"

[workspace.dependencies]
ctrlvim-types = { path = "crates/ctrlvim-types" }
ctrlvim-text = { path = "crates/ctrlvim-text" }
ctrlvim-options = { path = "crates/ctrlvim-options" }
ctrlvim-editor = { path = "crates/ctrlvim-editor" }
ctrlvim-vimscript = { path = "crates/ctrlvim-vimscript" }
ctrlvim-treesitter = { path = "crates/ctrlvim-treesitter" }
ctrlvim-markdown = { path = "crates/ctrlvim-markdown" }
ctrlvim-api-macro = { path = "crates/ctrlvim-api-macro" }
ctrlvim-api = { path = "crates/ctrlvim-api" }
ctrlvim-lua = { path = "crates/ctrlvim-lua" }
ctrlvim-async = { path = "crates/ctrlvim-async" }
ctrlvim-core = { path = "crates/ctrlvim-core" }

ratatui = "0.29"
crossterm = "0.28"
ropey = "1.6"
mlua = { version = "0.9", features = ["lua54", "vendored"] }
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time", "process", "net", "io-util", "macros"] }
rmpv = "1"
thiserror = "1"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
