//! Vimscript builtin functions (`vim.fn.*` / `f_*` in `eval/funcs.c`).
//!
//! This is a representative slice generated by hand; Neovim generates ~700 of
//! these from `eval.lua`. Editor-aware builtins receive an [`EditorAccess`].
//! Returns `None` if the function name is unknown (so the interpreter can raise
//! "Unknown function").

use crate::interp::EditorAccess;
use crate::value::{self, to_number, to_string, type_code};
use nvim_types::{Error, Object, Result};

/// Dispatch a builtin call. `None` = unknown function.
pub fn call(name: &str, args: &[Object], editor: &mut dyn EditorAccess) -> Option<Result<Object>> {
    let r = match name {
        "len" => Ok(Object::Integer(len(args.first()))),
        "empty" => Ok(Object::Integer(is_empty(args.first()) as i64)),
        "type" => Ok(Object::Integer(type_code(arg(args, 0)))),
        "str2nr" => Ok(Object::Integer(to_number(arg(args, 0)))),
        "string" => Ok(Object::str(to_string(arg(args, 0)))),
        "abs" => Ok(Object::Integer(to_number(arg(args, 0)).abs())),
        "float2nr" => Ok(Object::Integer(to_number(arg(args, 0)))),
        "toupper" => Ok(Object::str(to_string(arg(args, 0)).to_uppercase())),
        "tolower" => Ok(Object::str(to_string(arg(args, 0)).to_lowercase())),
        "trim" => Ok(Object::str(to_string(arg(args, 0)).trim().to_string())),
        "strlen" => Ok(Object::Integer(to_string(arg(args, 0)).len() as i64)),
        "strchars" => Ok(Object::Integer(to_string(arg(args, 0)).chars().count() as i64)),
        "split" => Ok(split(args)),
        "join" => Ok(join(args)),
        "range" => Ok(range(args)),
        "add" => add(args),
        "get" => Ok(get(args)),
        "has_key" => Ok(Object::Integer(has_key(args) as i64)),
        "keys" => Ok(keys(args)),
        "values" => Ok(values(args)),
        "max" => Ok(Object::Integer(list_reduce(args, i64::MIN, |a, b| a.max(b)))),
        "min" => Ok(Object::Integer(list_reduce(args, i64::MAX, |a, b| a.min(b)))),
        "sort" => Ok(sort(args)),
        "reverse" => Ok(reverse(args)),
        "printf" => Ok(Object::str(printf(args))),
        "substitute" => Ok(substitute(args)),
        "stridx" => Ok(Object::Integer(stridx(args))),
        "has" => Ok(Object::Integer(has_feature(args) as i64)),
        "exists" => Ok(Object::Integer(0)), // conservative: nothing exists yet
        // editor-aware
        "line" => Ok(Object::Integer(line(args, editor))),
        "col" => Ok(Object::Integer(editor.cursor().1)),
        "getline" => Ok(Object::str(editor.get_line(to_number(arg(args, 0))))),
        "setline" => {
            editor.set_line(to_number(arg(args, 0)), &to_string(arg(args, 1)));
            Ok(Object::Integer(0))
        }
        "line2byte" => Ok(Object::Integer(1)),
        _ => return None,
    };
    Some(r)
}

fn arg(args: &[Object], i: usize) -> &Object {
    args.get(i).unwrap_or(&Object::Nil)
}

fn len(o: Option<&Object>) -> i64 {
    match o {
        Some(Object::Array(a)) => a.len() as i64,
        Some(Object::Dict(d)) => d.len() as i64,
        Some(Object::String(s)) => s.len() as i64,
        _ => 0,
    }
}

fn is_empty(o: Option<&Object>) -> bool {
    match o {
        Some(Object::Array(a)) => a.is_empty(),
        Some(Object::Dict(d)) => d.is_empty(),
        Some(Object::String(s)) => s.is_empty(),
        Some(Object::Integer(i)) => *i == 0,
        Some(Object::Nil) | None => true,
        _ => false,
    }
}

fn split(args: &[Object]) -> Object {
    let s = to_string(arg(args, 0));
    let parts: Vec<Object> = if args.len() > 1 {
        let sep = to_string(arg(args, 1));
        s.split(&sep).filter(|p| !p.is_empty()).map(Object::str).collect()
    } else {
        s.split_whitespace().map(Object::str).collect()
    };
    Object::Array(parts)
}

fn join(args: &[Object]) -> Object {
    let sep = if args.len() > 1 { to_string(arg(args, 1)) } else { " ".to_string() };
    match arg(args, 0) {
        Object::Array(items) => {
            let parts: Vec<String> = items.iter().map(to_string).collect();
            Object::str(parts.join(&sep))
        }
        _ => Object::str(String::new()),
    }
}

fn range(args: &[Object]) -> Object {
    let (start, end, step) = match args.len() {
        1 => (0, to_number(arg(args, 0)) - 1, 1),
        2 => (to_number(arg(args, 0)), to_number(arg(args, 1)), 1),
        _ => (to_number(arg(args, 0)), to_number(arg(args, 1)), to_number(arg(args, 2)).max(1)),
    };
    let mut out = Vec::new();
    let mut i = start;
    while i <= end {
        out.push(Object::Integer(i));
        i += step;
    }
    Object::Array(out)
}

fn add(args: &[Object]) -> Result<Object> {
    match arg(args, 0) {
        Object::Array(items) => {
            let mut new = items.clone();
            new.push(arg(args, 1).clone());
            Ok(Object::Array(new))
        }
        _ => Err(Error::exception("add() requires a list")),
    }
}

fn get(args: &[Object]) -> Object {
    let default = args.get(2).cloned().unwrap_or(Object::Nil);
    match arg(args, 0) {
        Object::Array(items) => {
            let i = to_number(arg(args, 1));
            items.get(i.max(0) as usize).cloned().unwrap_or(default)
        }
        Object::Dict(map) => map.get(&to_string(arg(args, 1))).cloned().unwrap_or(default),
        _ => default,
    }
}

fn has_key(args: &[Object]) -> bool {
    matches!(arg(args, 0), Object::Dict(map) if map.contains_key(&to_string(arg(args, 1))))
}

fn keys(args: &[Object]) -> Object {
    match arg(args, 0) {
        Object::Dict(map) => Object::Array(map.keys().map(|k| Object::str(k.clone())).collect()),
        _ => Object::Array(vec![]),
    }
}

fn values(args: &[Object]) -> Object {
    match arg(args, 0) {
        Object::Dict(map) => Object::Array(map.values().cloned().collect()),
        _ => Object::Array(vec![]),
    }
}

fn list_reduce(args: &[Object], init: i64, f: impl Fn(i64, i64) -> i64) -> i64 {
    match arg(args, 0) {
        Object::Array(items) if !items.is_empty() => {
            items.iter().map(to_number).fold(init, f)
        }
        _ => 0,
    }
}

fn sort(args: &[Object]) -> Object {
    match arg(args, 0) {
        Object::Array(items) => {
            let mut v = items.clone();
            // Default Vim sort is lexical by string representation.
            v.sort_by(|a, b| to_string(a).cmp(&to_string(b)));
            Object::Array(v)
        }
        other => other.clone(),
    }
}

fn reverse(args: &[Object]) -> Object {
    match arg(args, 0) {
        Object::Array(items) => {
            let mut v = items.clone();
            v.reverse();
            Object::Array(v)
        }
        other => other.clone(),
    }
}

fn stridx(args: &[Object]) -> i64 {
    let haystack = to_string(arg(args, 0));
    let needle = to_string(arg(args, 1));
    haystack.find(&needle).map(|b| b as i64).unwrap_or(-1)
}

fn substitute(args: &[Object]) -> Object {
    // substitute(str, pat, sub, flags) — literal replace (no regex yet).
    let s = to_string(arg(args, 0));
    let pat = to_string(arg(args, 1));
    let sub = to_string(arg(args, 2));
    let flags = to_string(arg(args, 3));
    let result = if flags.contains('g') {
        s.replace(&pat, &sub)
    } else {
        s.replacen(&pat, &sub, 1)
    };
    Object::str(result)
}

fn printf(args: &[Object]) -> String {
    // A tiny printf supporting %s, %d, %%.
    let fmt = to_string(arg(args, 0));
    let mut out = String::new();
    let mut argi = 1;
    let mut chars = fmt.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '%' {
            match chars.next() {
                Some('%') => out.push('%'),
                Some('s') => {
                    out.push_str(&to_string(arg(args, argi)));
                    argi += 1;
                }
                Some('d') => {
                    out.push_str(&to_number(arg(args, argi)).to_string());
                    argi += 1;
                }
                Some(other) => {
                    out.push('%');
                    out.push(other);
                }
                None => out.push('%'),
            }
        } else {
            out.push(c);
        }
    }
    out
}

fn has_feature(args: &[Object]) -> bool {
    // Report the features a modern Lua-first setup relies on.
    matches!(to_string(arg(args, 0)).as_str(), "nvim" | "lua" | "unix")
}

fn line(args: &[Object], editor: &mut dyn EditorAccess) -> i64 {
    match to_string(arg(args, 0)).as_str() {
        "$" => editor.line_count(),
        "." => editor.cursor().0,
        _ => editor.cursor().0,
    }
}

// Re-export for the interpreter's convenience.
pub use value::to_string as value_to_string;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::interp::NullEditor;

    fn c(name: &str, args: &[Object]) -> Object {
        let mut ed = NullEditor::default();
        call(name, args, &mut ed).unwrap().unwrap()
    }

    #[test]
    fn builtin_len() {
        assert_eq!(c("len", &[Object::Array(vec![Object::Integer(1), Object::Integer(2)])]), Object::Integer(2));
    }

    #[test]
    fn builtin_split_join() {
        let parts = c("split", &[Object::str("a,b,c"), Object::str(",")]);
        assert_eq!(parts, Object::Array(vec![Object::str("a"), Object::str("b"), Object::str("c")]));
        let joined = c("join", &[parts, Object::str("-")]);
        assert_eq!(joined, Object::str("a-b-c"));
    }

    #[test]
    fn builtin_range() {
        assert_eq!(
            c("range", &[Object::Integer(1), Object::Integer(3)]),
            Object::Array(vec![Object::Integer(1), Object::Integer(2), Object::Integer(3)])
        );
    }

    #[test]
    fn builtin_printf() {
        assert_eq!(c("printf", &[Object::str("%s=%d"), Object::str("x"), Object::Integer(7)]), Object::str("x=7"));
    }

    #[test]
    fn builtin_substitute_global() {
        assert_eq!(
            c("substitute", &[Object::str("aaa"), Object::str("a"), Object::str("b"), Object::str("g")]),
            Object::str("bbb")
        );
    }

    #[test]
    fn unknown_function_returns_none() {
        let mut ed = NullEditor::default();
        assert!(call("no_such_fn", &[], &mut ed).is_none());
    }
}
