//! Lua embedding: the `mlua`-backed replacement for `executor.c` +
//! `converter.c`.
//!
//! Exposes [`Host`], which owns the Lua state and the editor, installs the
//! `vim.api` surface generated by `ctrlvim-api`, converts values across the
//! boundary ([`convert`]), and holds/invokes Lua callbacks ([`reg::LuaRefStore`]).

pub mod convert;
pub mod host;
pub mod reg;

pub use host::Host;
pub use reg::LuaRefStore;
