//! The API function registry — the runtime side of the codegen pipeline.
//!
//! Neovim's `gen_api_dispatch.lua` emits a `method_handlers[]` table (indexed by
//! a perfect hash) mapping method name → handler. We use the `inventory` crate:
//! every `#[ctrlvim_api]` function `submit!`s an [`ApiFunction`] at link time, and
//! [`call`] looks one up by name. A `HashMap` replaces the perfect hash (Rust
//! doesn't need the C micro-optimization).

use crate::ApiContext;
use ctrlvim_types::{Error, Object, Result};
use std::collections::HashMap;
use std::sync::OnceLock;

/// A registered API function, contributed by the `#[ctrlvim_api]` macro.
pub struct ApiFunction {
    pub name: &'static str,
    /// API level the function was introduced (Neovim's `FUNC_API_SINCE`).
    pub since: u32,
    /// Safe to call from a fast/async context (`FUNC_API_FAST`).
    pub fast: bool,
    /// Type-erased dispatch shim generated by the macro.
    pub dispatch: fn(&mut ApiContext, &[Object]) -> Result<Object>,
}

inventory::collect!(ApiFunction);

/// All registered API functions.
pub fn all() -> impl Iterator<Item = &'static ApiFunction> {
    inventory::iter::<ApiFunction>.into_iter()
}

fn index() -> &'static HashMap<&'static str, &'static ApiFunction> {
    static INDEX: OnceLock<HashMap<&'static str, &'static ApiFunction>> = OnceLock::new();
    INDEX.get_or_init(|| all().map(|f| (f.name, f)).collect())
}

/// Look up a function descriptor by name.
pub fn lookup(name: &str) -> Option<&'static ApiFunction> {
    index().get(name).copied()
}

/// Dispatch an API call by name — the single entry point shared by both the Lua
/// binding and the msgpack-RPC handler.
pub fn call(cx: &mut ApiContext, name: &str, args: &[Object]) -> Result<Object> {
    match lookup(name) {
        Some(f) => (f.dispatch)(cx, args),
        None => Err(Error::exception(format!("unknown API function: {}", name))),
    }
}

/// Number of registered functions (used by `ctrlvim_get_api_info`-style queries).
pub fn count() -> usize {
    all().count()
}
